/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ValuesImport } from './routes/values'
import { Route as IndexImport } from './routes/index'
import { Route as ValuesKeyImport } from './routes/values.$key'

// Create/Update Routes

const ValuesRoute = ValuesImport.update({
  id: '/values',
  path: '/values',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ValuesKeyRoute = ValuesKeyImport.update({
  id: '/$key',
  path: '/$key',
  getParentRoute: () => ValuesRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/values': {
      id: '/values'
      path: '/values'
      fullPath: '/values'
      preLoaderRoute: typeof ValuesImport
      parentRoute: typeof rootRoute
    }
    '/values/$key': {
      id: '/values/$key'
      path: '/$key'
      fullPath: '/values/$key'
      preLoaderRoute: typeof ValuesKeyImport
      parentRoute: typeof ValuesImport
    }
  }
}

// Create and export the route tree

interface ValuesRouteChildren {
  ValuesKeyRoute: typeof ValuesKeyRoute
}

const ValuesRouteChildren: ValuesRouteChildren = {
  ValuesKeyRoute: ValuesKeyRoute,
}

const ValuesRouteWithChildren =
  ValuesRoute._addFileChildren(ValuesRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/values': typeof ValuesRouteWithChildren
  '/values/$key': typeof ValuesKeyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/values': typeof ValuesRouteWithChildren
  '/values/$key': typeof ValuesKeyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/values': typeof ValuesRouteWithChildren
  '/values/$key': typeof ValuesKeyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/values' | '/values/$key'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/values' | '/values/$key'
  id: '__root__' | '/' | '/values' | '/values/$key'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ValuesRoute: typeof ValuesRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ValuesRoute: ValuesRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/values"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/values": {
      "filePath": "values.tsx",
      "children": [
        "/values/$key"
      ]
    },
    "/values/$key": {
      "filePath": "values.$key.tsx",
      "parent": "/values"
    }
  }
}
ROUTE_MANIFEST_END */
