/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DataImport } from './routes/data'
import { Route as IndexImport } from './routes/index'
import { Route as DataKeyImport } from './routes/data.$key'
import { Route as DataKeyEditImport } from './routes/data.$key.edit'

// Create/Update Routes

const DataRoute = DataImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DataKeyRoute = DataKeyImport.update({
  id: '/$key',
  path: '/$key',
  getParentRoute: () => DataRoute,
} as any)

const DataKeyEditRoute = DataKeyEditImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => DataKeyRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataImport
      parentRoute: typeof rootRoute
    }
    '/data/$key': {
      id: '/data/$key'
      path: '/$key'
      fullPath: '/data/$key'
      preLoaderRoute: typeof DataKeyImport
      parentRoute: typeof DataImport
    }
    '/data/$key/edit': {
      id: '/data/$key/edit'
      path: '/edit'
      fullPath: '/data/$key/edit'
      preLoaderRoute: typeof DataKeyEditImport
      parentRoute: typeof DataKeyImport
    }
  }
}

// Create and export the route tree

interface DataKeyRouteChildren {
  DataKeyEditRoute: typeof DataKeyEditRoute
}

const DataKeyRouteChildren: DataKeyRouteChildren = {
  DataKeyEditRoute: DataKeyEditRoute,
}

const DataKeyRouteWithChildren =
  DataKeyRoute._addFileChildren(DataKeyRouteChildren)

interface DataRouteChildren {
  DataKeyRoute: typeof DataKeyRouteWithChildren
}

const DataRouteChildren: DataRouteChildren = {
  DataKeyRoute: DataKeyRouteWithChildren,
}

const DataRouteWithChildren = DataRoute._addFileChildren(DataRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data': typeof DataRouteWithChildren
  '/data/$key': typeof DataKeyRouteWithChildren
  '/data/$key/edit': typeof DataKeyEditRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data': typeof DataRouteWithChildren
  '/data/$key': typeof DataKeyRouteWithChildren
  '/data/$key/edit': typeof DataKeyEditRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/data': typeof DataRouteWithChildren
  '/data/$key': typeof DataKeyRouteWithChildren
  '/data/$key/edit': typeof DataKeyEditRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/data' | '/data/$key' | '/data/$key/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/data' | '/data/$key' | '/data/$key/edit'
  id: '__root__' | '/' | '/data' | '/data/$key' | '/data/$key/edit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataRoute: typeof DataRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataRoute: DataRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/data"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/data": {
      "filePath": "data.tsx",
      "children": [
        "/data/$key"
      ]
    },
    "/data/$key": {
      "filePath": "data.$key.tsx",
      "parent": "/data",
      "children": [
        "/data/$key/edit"
      ]
    },
    "/data/$key/edit": {
      "filePath": "data.$key.edit.tsx",
      "parent": "/data/$key"
    }
  }
}
ROUTE_MANIFEST_END */
