name: build-artifacts
on:
  push:
    branches: [main]
permissions:
  contents: write
env:
  CARGO_TERM_COLOR: always
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
          toolchain: 1.85.0
      - uses: Swatinem/rust-cache@v2
      - uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: |
            types/package-lock.json
            client/package-lock.json
          node-version: 20
      - name: "Install NPM Deps: types"
        working-directory: types
        run: npm ci
      - name: "Install NPM Deps: client"
        working-directory: client
        run: npm ci
      - name: Install just
        uses: taiki-e/install-action@v2
        with:
          tool: just
      - name: Verify
        run: just verify
  build:
    runs-on: ubuntu-latest
    needs: [verify]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
          toolchain: 1.85.0
      - uses: Swatinem/rust-cache@v2
      - uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: |
            types/package-lock.json
            client/package-lock.json
          node-version: 20
      - name: "Install NPM Deps: types"
        working-directory: types
        run: npm ci
      - name: "Install NPM Deps: client"
        working-directory: client
        run: npm ci
      - name: Install just
        uses: taiki-e/install-action@v2
        with:
          tool: just
      - name: Build
        run: just build-release
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: rust-web-app
          path: target/release/rust-web-app
  build-mac:
    runs-on: macos-latest
    needs: [verify]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
          toolchain: 1.85.0
      - uses: Swatinem/rust-cache@v2
      - uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: |
            types/package-lock.json
            client/package-lock.json
          node-version: 20
      - name: "Install NPM Deps: types"
        working-directory: types
        run: npm ci
      - name: "Install NPM Deps: client"
        working-directory: client
        run: npm ci
      - name: Install just
        uses: taiki-e/install-action@v2
        with:
          tool: just
      - name: Build
        run: just build-release
      - name: Upload CLI Binary
        uses: actions/upload-artifact@v4
        with:
          name: rust-web-app (macos)
          path: target/release/rust-web-app
  build-windows:
    runs-on: windows-latest
    needs: [verify]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
          toolchain: 1.85.0
      - uses: Swatinem/rust-cache@v2
      - uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: |
            types/package-lock.json
            client/package-lock.json
          node-version: 20
      - name: "Install NPM Deps: types"
        working-directory: types
        run: npm ci
      - name: "Install NPM Deps: client"
        working-directory: client
        run: npm ci
      - name: Install just
        uses: taiki-e/install-action@v2
        with:
          tool: just
      - name: Build
        run: just build-release
      - name: Upload CLI Binary
        uses: actions/upload-artifact@v4
        with:
          name: rust-web-app.exe
          path: target/release/rust-web-app.exe
